## 项目端口
server:
  port: 8083
  servlet:
    context-path: /idataclient

## 日志打印
logging:
  level:
    com.fangtang.waterenvironment.mapper: info
  config: classpath:logback-spring.xml

backend.uri: http://10.10.10.81:8010/idataservice
task.basedir: /root/task/
